name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Adjust to your target branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2: Build the project (if needed)
      # Skip this step if your static files are prebuilt
      #- name: Build the project
      #  run: npm install && npm run build

      # Step 3: Upload the static files as an artifact
      - name: Upload static files
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist # Adjust this to the folder containing your static site files

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
