name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Adjust this to your branch name

permissions:
  contents: read
  pages: write
  id-token: write # Add this line for the deploy-pages action

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Upload built content to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          folder: dist # Specify the dist folder as the source
