name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Adjust to your target branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Install dependencies and build the project
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # Step 3: Upload the static files as an artifact (Updated to v4)
      - name: Upload static files
        uses: actions/upload-pages-artifact@v2 # Update to v2
        with:
          path: dist # Adjust this to your build output folder

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
